---
language: python
services:
  - docker

os: linux
dist: bionic

env:
  global:
    - COLLECTION_NAMESPACE: "networktocode"
    - COLLECTION_NAME: "nautobot"
    - COLLECTION_VERSION: "1.0.0"
    - secure: "tE6GtwrRU+Kjobx/94xqR2MqM20pHCnrLcHgPzIHA3npdwuA+GjCBiBLTkEEQM4fUWIfzUTyjSr9bZErm1PTI1GcIRdniTgJ3ZzSSkE7tgeYALB/7xsusB57SlmbBQm2SGwU558uWZ3NHEsi0WTgD8GKZo77OpGX72FZKsVXOz6k2wve51sOtoSVjgCsvWTmZHx4ynGdiA5wFkZfaEcjXECahKtunW+MlB5kpJzkVeLRUEXFMhWlsIYiA5nj8OI/X3Nk9ugh1ribENX9LrjpgrqQ9YariZ8G6py1ONuKZIn2g7xs5kNQ3qL6HL6N7SoUxiwH16CfSyugFaYiMfaxQ4NUVGGRHS4vSGbNIf+gLHcYvP40miI1f/+pntCzqygZMhW73FX2o+KH2OGv09khOl8k1nDg2/XvW0kCc/FU6l+Jp5wCC8H9X2uiULtQpRqts5TzIonlPEzGIpfGFgJ5m54Emhv9gjG1Z5OOyL/qae1Wr+L/uhiFafcglZYh8NHEMWCUCkeqFqR2kDmUMtdgYLD7Q7NdwlL/PSVVs1l7UPiQHlnecQKEHN7CvR3eKByTEmkCKafRYh/JQ9rBt9sZc7aAPVu+w3wWUwbHS4o4vVnmyXvJb1PeJSiuynF7CBo4Qd6qj4YwX8gLK6PylGyaMOp169u6xw1mo5/CX0pJ3x4="

jobs:
  include:
    - name: "Python 3.6 - Nautobot - Latest PyPi Ansible"
      python: 3.6
      env:
        - PYTHON_VER=3.6
      install:
        - pip install -U pip
        - pip install poetry
        - poetry config virtualenvs.create false && poetry install

before_script:
  - mkdir -p ~/ansible_collections/$COLLECTION_NAMESPACE
  - ansible-galaxy collection build .
  - ansible-galaxy collection install $COLLECTION_NAMESPACE-$COLLECTION_NAME*.tar.gz -p /home/travis/.ansible/collections

  # Run all further tests from within the installed directory
  # Required to resolve imports of other collections
  - cd /home/travis/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Check python syntax
  - black . --check --diff

  # Sanity tests
  # --requirements - install pip packages as necessary
  # Skip pep8 as we use black instead
  - ansible-test sanity -v --requirements --python $PYTHON_VER --skip-test pep8 plugins/

  # Unit tests, with code coverage
  - ansible-test units -v --coverage --python $PYTHON_VER
  # Report code coverage
  - ansible-test coverage report --all --omit "tests/*,hacking/*,docs/*" --show-missing

deploy:
  provider: script
  skip_cleanup: true
  script: ansible-galaxy collection publish ~/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME/$COLLECTION_NAMESPACE-$COLLECTION_NAME-$COLLECTION_VERSION.tar.gz --api-key="$GALAXY_API_TOKEN"
  on:
    tags: true
