[tool.poetry]
name = "nautobot_ansible_modules"
version = "1.0.0"
description = "Ansible collection to interact with Nautobot's API"
authors = ["Network to Code <info@networktocode.com"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.6"
ansible-base = "^2.10.0"
black = "19.10b0"
codecov = "*"
coverage = "^4.0"
cryptography = "*"
jinja2 = "*"
jmespath = "*"
jsondiff = "*"
pynetbox = "*"
pytest = "*"
pytest-mock = "*"
pytest-xdist = "*"
pyyaml = "*"
mock = "^4.0.2"
antsibull = "^0.25.0"
importlib-metadata = "1.7.0"
pylint = "^2.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
